name: Build and Push

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Install dependencies
        run: go mod download
      
      - name: Run Makefile
        run: make
      

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      
      - name: Run go fmt
        run: go fmt ./...
      
      - name: Run golangci-lint
        run: golangci-lint run ./...
        
      - name: Run staticcheck
        run: staticcheck ./...
